plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.143'
    id 'maven-publish'
}

version = minecraft_version + "-" + mod_version
group = modGroup

sourceSets {
    main {
        java {
            exclude 'com/buuz135/functionalstorage/compat/top/**'
        }
        resources.srcDir('src/generated/resources')
    }
}

repositories {
    maven {
        name = "BlameJared maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        url = "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

base {
    archivesName = modBaseName
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = "${neo_version}"

    validateAccessTransformers = true

    runs {
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
        clientData {
            clientData()
            programArguments.addAll '--mod', 'functionalstorage', '--all', '--uncached', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        serverData {
            serverData()
            programArguments.addAll '--mod', 'functionalstorage', '--all', '--uncached', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }

    mods {
        functionalstorage {
            sourceSet sourceSets.main
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
    localRuntime "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"

    implementation "com.hrznstudio:titanium:${titanium_version}"

    compileOnly "curse.maven:jade-324717:8651070"
    localRuntime "curse.maven:jade-324717:8651070"
    compileOnly "curse.maven:ftb-library-forge-404465:8574542"
    compileOnly "curse.maven:ftb-teams-forge-404468:8074003"
    compileOnly "curse.maven:ftb-chunks-forge-314906:8574590"
    localRuntime "curse.maven:ftb-library-forge-404465:8574542"
    localRuntime "curse.maven:ftb-teams-forge-404468:8074003"
    localRuntime "curse.maven:ftb-chunks-forge-314906:8574590"

    localRuntime "curse.maven:applied-energistics-2-223794:9022271"
    localRuntime "curse.maven:guideme-1173950:9022838"
}

jar {
    manifest {
        attributes(["Specification-Title"     : project.name,
                    "Specification-Vendor"    : "Buuz135, Rid",
                    "Specification-Version"   : "1.0",
                    "Implementation-Title"    : project.name,
                    "Implementation-Version"  : "${project.version}",
                    "Implementation-Vendor"   : "Buuz135, Rid",
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                    "ModSide"                 : "BOTH"
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
    options.compilerArgs << '-Xmaxerrs' << '500'
}

publishing {
  publications {
    mavenJava(MavenPublication) {
      from components.java
    }
  }
  repositories {
    maven {
      name = 'repo'
      url = file('repo')
    }
  }
}
